# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-16 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_note', models.TextField(blank=True)),
                ('token', models.CharField(max_length=6)),
                ('timestamp', models.DateTimeField(verbose_name='Created on')),
            ],
        ),
    ]
